### ISSUE TITLE
Dependency Not Noted

### ISSUE THREAD

**Issue by maxwell-gh** [Real-Gecko/KSP-SimpleConstruction#1]
The Ore Tanks require [InterstellarFuelSwitch](https://kerbal.curseforge.com/projects/interstellar-fuel-switch) in order to function properly to hold Metal. This should be noted in the README with ModuleManager.

**Comment by Real-Gecko** [comment]
OK, I'll note it in README, but if you install with CKAN, then you'll be fine without README.

**Comment by maxwell-gh** [comment]
Good to know! I don't have CKAN, so it took me a second to figure out why the OreTanks weren't working. I figured it'd be nice to have that for non-CKAN users. I'll mark it as closed!

**Comment by Real-Gecko** [comment]
Oh yeah, I tried to manage mods manually, it's a hell :D :D :D
