### ISSUE TITLE
Cant finalized build

### ISSUE THREAD

**Issue by drami713** [Real-Gecko/KSP-SimpleConstruction#5]
Recently, after the KSP 1.3.1 update, the finalize build button hasn't been working. The button is just like normal (not greyed out) but upon pressing the button nothing happens. I've tried installing both manually and through CKAN but the problem persists. Im running KSP windows 64 bit. If any other specs or info is required, I can provide it. Thanks!

EDIT: I do know KSP 1.3.1 isn't supported yet.

**Comment by Real-Gecko** [comment]
Looks like it's the EL problem
https://forum.kerbalspaceprogram.com/index.php?/topic/54284-13-extraplanetary-launchpads-v582/&do=findComment&comment=3192046
I think it was reckless from my side to mark SC as compatible without extensive testing.
There's already a bug report in main EL repo https://github.com/taniwha/Extraplanetary-Launchpads/issues/131
So, everything that remains is to wait.
